### ISSUE TITLE
make test failed on basic

### ISSUE THREAD

**Issue by fpestiaux-cplus** [alanxz/rabbitmq-c#530]
Hello I do have a fail test when i run 'make test' with the lastest source on Centos 7.5
What is basic ? Any idea why this is breaking ?

```
[root@kevin-cplus build]# make test
Running tests...
Test project /root/rabbitmq-c-0.9.0/build
    Start 1: parse_url
1/7 Test #1: parse_url ........................   Passed    0.00 sec
    Start 2: tables
2/7 Test #2: tables ...........................   Passed    0.00 sec
    Start 3: hostcheck
3/7 Test #3: hostcheck ........................   Passed    0.00 sec
    Start 4: status_enum
4/7 Test #4: status_enum ......................   Passed    0.00 sec
    Start 5: basic
5/7 Test #5: basic ............................***Exception: Other  0.00 sec
    Start 6: sasl_mechanism
6/7 Test #6: sasl_mechanism ...................   Passed    0.00 sec
    Start 7: merge_capabilities
7/7 Test #7: merge_capabilities ...............   Passed    0.00 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) =   0.02 sec

The following tests FAILED:
	  5 - basic (OTHER_FAULT)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by Whissi** [comment]
Same on Gentoo:
```
5/7 Testing: basic
5/7 Test: basic
Command: "/var/tmp/portage/net-libs/rabbitmq-c-0.9.0/work/rabbitmq-c-0.9.0_build/tests/test_basic"
Directory: /var/tmp/portage/net-libs/rabbitmq-c-0.9.0/work/rabbitmq-c-0.9.0_build/tests
"basic" start time: Dec 19 13:19 CET
Output:
----------------------------------------------------------
test_basic: /var/tmp/portage/net-libs/rabbitmq-c-0.9.0/work/rabbitmq-c-0.9.0/tests/test_basic.c:54: setup_connection_and
_channel: Assertion `rc == AMQP_STATUS_OK' failed.
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"basic" end time: Dec 19 13:19 CET
"basic" time elapsed: 00:00:00
----------------------------------------------------------


(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f7f0578d535 in __GI_abort () at abort.c:79
#2  0x00007f7f0578d40f in __assert_fail_base (fmt=0x7f7f05904e98 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x560dc0c1514b "rc == AMQP_STATUS_OK",
    file=0x560dc0c15008 "/var/tmp/portage/net-libs/rabbitmq-c-0.9.0/work/rabbitmq-c-0.9.0/tests/test_basic.c",
    line=54, function=<optimized out>) at assert.c:92
#3  0x00007f7f0579bea2 in __GI___assert_fail (assertion=0x560dc0c1514b "rc == AMQP_STATUS_OK",
    file=0x560dc0c15008 "/var/tmp/portage/net-libs/rabbitmq-c-0.9.0/work/rabbitmq-c-0.9.0/tests/test_basic.c",
    line=54, function=0x560dc0c15220 <__PRETTY_FUNCTION__.4684> "setup_connection_and_channel") at assert.c:101
#4  0x0000560dc0c073ed in setup_connection_and_channel ()
    at /var/tmp/portage/net-libs/rabbitmq-c-0.9.0/work/rabbitmq-c-0.9.0/tests/test_basic.c:54
#5  0x0000560dc0c07806 in publish_and_basic_get_message (msg_to_publish=0x560dc0c15254 "")
    at /var/tmp/portage/net-libs/rabbitmq-c-0.9.0/work/rabbitmq-c-0.9.0/tests/test_basic.c:142
#6  0x0000560dc0c07b13 in main ()
    at /var/tmp/portage/net-libs/rabbitmq-c-0.9.0/work/rabbitmq-c-0.9.0/tests/test_basic.c:200
```

**Comment by Whissi** [comment]
Test is failing because it requires a running and accessible RabbitMQ server instance on localhost. When you view Travis' log, you see that it is starting such an instance https://travis-ci.org/alanxz/rabbitmq-c/jobs/469382139#L418

**Comment by alanxz** [comment]
As of #604, tests requiring a broker are no longer required.
