### ISSUE TITLE
App crashes when heartbeat != 0

### ISSUE THREAD

**Issue by yasenchak4J** [alanxz/rabbitmq-c#563]
I connect to the rmq server like this:

`struct timeval tm;
    tm.tv_sec = 15;
    conn = amqp_new_connection();
    //socket = amqp_tcp_socket_new(conn);
    socket = amqp_ssl_socket_new(conn);
    if (!socket) {
        die("creating SSL socket");
    }
    const char *host = hostname.constData();
    const char *user = amqp_user.constData();
    const char *pass = amqp_pass.constData();
    const char *virtHost = vHost.constData();
    amqp_ssl_socket_set_verify_peer(socket, 0);
    amqp_ssl_socket_set_verify_hostname(socket, 0);
    //status = amqp_socket_open(socket, host, port);
    status = amqp_socket_open_noblock(socket, host, port, &tm);
    if (status) {
        qDebug()<< "socket not open";
    }

die_on_amqp_error(amqp_login(conn, virtHost, 0, 131072, 15, AMQP_SASL_METHOD_PLAIN, user, pass), "Logging in");

amqp_channel_open(conn, 1);
die_on_amqp_error(amqp_get_rpc_reply(conn), "Opening channel");`

Consumer code: 

`amqp_basic_consume(conn, 1, amqp_cstring_bytes("device." + GlobalsArgs::amqp_user), amqp_empty_bytes,
                       0, 0, 0, amqp_empty_table);
    die_on_amqp_error(amqp_get_rpc_reply(conn), "Consuming");
                bool ok = true;
                amqp_rpc_reply_t res;
                amqp_envelope_t envelope;
                amqp_maybe_release_buffers(conn);
                // waiting for a packet
                res = amqp_consume_message(conn, &envelope, NULL, 0);
                
                qDebug()<< res.library_error;
                
                if (res.reply_type != AMQP_RESPONSE_NORMAL) {
                    qDebug()<< res.library_error;
                    try { amqp_destroy_envelope(&envelope); } catch (...) {  }
                    ok = false;
                    continue;
                }

                ackEnvelope = true;

                if (ackEnvelope) {
                    ok = (amqp_basic_ack(conn, 1, envelope.delivery_tag, 0) == 0);
                } else {
                    amqp_basic_nack(conn, 1, envelope.delivery_tag, 0, true);
                    ok = false;
                }
                QBuffer typeProperties;
                typeProperties.setData((char *) envelope.message.properties.type.bytes, envelope.message.properties.type.len);
                typeProperties.open(QIODevice::ReadOnly);
                QByteArray byteProperties = typeProperties.readAll();
                typeProperties.close();
                QBuffer message;
                message.setData((char *) envelope.message.body.bytes, envelope.message.body.len);
                message.open(QIODevice::ReadOnly);
                QByteArray messageJson = message.readAll();
                message.close();
                if(byteProperties != ""){
                    emit reciveMessage(messageJson, byteProperties);
                }

                amqp_destroy_envelope(&envelope);`

When i set heartbeat value != 0 my consumer crashes.

![image](https://user-images.githubusercontent.com/37080669/58010936-fc4f1f80-7af9-11e9-9415-701675e36675.png)
stack trace 
1  _threadid                          ucrtbased             0x7fedc784f75 
2  _threadid                          ucrtbased             0x7fedc785113 
3  abort                              ucrtbased             0x7fedc799d6d 
4  amqp_abort                         amqp_api.c        182 0x7fee521357c 
5  wait_frame_inner                   amqp_socket.c     826 0x7fee521956b 
6  amqp_simple_wait_frame_noblock     amqp_socket.c     960 0x7fee5216c55 
7  amqp_consume_message               amqp_consumer.c   147 0x7fee52206b8 
8  GetMessageRMQ::startConsume        getmessagermq.cpp 30  0x13f394254   
9  GetMessageRMQ::startGetMessageForm getmessagermq.cpp 103 0x13f394868   
10 GetMessageRMQ::run                 getmessagermq.cpp 19  0x13f394153   
11 QThreadPrivate::start              qthread_win.cpp   380 0x7fed6b3721a 
12 BaseThreadInitThunk                kernel32              0x7735555d    
13 RtlUserThreadStart                 ntdll                 0x775b385d    

Value of local variable in debug mode:		
		deadline	@0xb55f668	amqp_time_t_
			time_point_ns	18446744073709551615	unsigned int64
		decoded_frame	@0xb55f6e8	amqp_frame_t_
			channel	0	unsigned short
			frame_type	    	8	0x08	unsigned char
			payload	@0xb55f6f0	<unnamed-tag>
		res	0	int
		state	@0x7324f00	amqp_connection_state_t_
			channel_max	2047	int
			client_properties	@0x7325040	amqp_table_t_
			first_queued_frame	0x0	amqp_link_t_*
			frame_max	131072	int
			handshake_timeout	@0x7325098	timeval
				tv_sec	12	long
				tv_usec	0	long
			header_buffer	"\010\000\000\000\000\000\000\000"	char[8]
			heartbeat	15	int
			inbound_buffer	@0x7324fa8	amqp_bytes_t_
			inbound_offset	0	unsigned int64
			internal_handshake_timeout	@0x7325098	timeval
			internal_rpc_timeout	@0x73250a8	timeval
			last_queued_frame	0x0	amqp_link_t_*
			most_recent_api_result	@0x7325010	amqp_rpc_reply_t_
			next_recv_heartbeat	@0x7324f90	amqp_time_t_
				time_point_ns	514776996760588	unsigned int64
			next_send_heartbeat	@0x7324f98	amqp_time_t_
				time_point_ns	514762047679165	unsigned int64
			outbound_buffer	@0x7324fc8	amqp_bytes_t_
			pool_table	@0x7324f00	amqp_pool_table_entry_t_*[16]
				[0]	@0x79d0c60	amqp_pool_table_entry_t_
					channel	0	unsigned short
					next	0x0	amqp_pool_table_entry_t_*
					pool	@0x79d0c68	amqp_pool_t_
				[1]	@0x7a9ec60	amqp_pool_table_entry_t_
				[2]	0x0	amqp_pool_table_entry_t_*
				[3]	0x0	amqp_pool_table_entry_t_*
				[4]	0x0	amqp_pool_table_entry_t_*
				[5]	0x0	amqp_pool_table_entry_t_*
				[6]	0x0	amqp_pool_table_entry_t_*
				[7]	0x0	amqp_pool_table_entry_t_*
				[8]	0x0	amqp_pool_table_entry_t_*
				[9]	0x0	amqp_pool_table_entry_t_*
				[10]	0x0	amqp_pool_table_entry_t_*
				[11]	0x0	amqp_pool_table_entry_t_*
				[12]	0x0	amqp_pool_table_entry_t_*
				[13]	0x0	amqp_pool_table_entry_t_*
				[14]	0x0	amqp_pool_table_entry_t_*
				[15]	0x0	amqp_pool_table_entry_t_*
			properties_pool	@0x7325050	amqp_pool_t_
				alloc_block	"authentication_failure_close"	char*
				alloc_used	312	unsigned int64
				large_blocks	@0x7325068	amqp_pool_blocklist_t_
				next_page	3	int
				pages	@0x7325058	amqp_pool_blocklist_t_
				pagesize	512	unsigned int64
			rpc_timeout	0x0	timeval*
			server_properties	@0x7325030	amqp_table_t_
			sock_inbound_buffer	@0x7324fe0	amqp_bytes_t_
			sock_inbound_limit	8	unsigned int64
			sock_inbound_offset	8	unsigned int64
			socket	@0x72cc8b0	amqp_socket_t_
				klass	@0x7fee5231540	amqp_socket_class_t
			state	CONNECTION_STATE_IDLE (0)	amqp_connection_state_enum_
			target_size	7	unsigned int64
		timeout	0x0	timeval*	
Any thoughts why this is happening?

**Comment by yasenchak4J** [comment]
and fmt = "Internal error: unable to determine timeout reason"

**Comment by Purushoth24051999** [comment]
I also face same issue but in linux when heartbeart is enabled

My GDB output:

```
Internal error: unable to determine timeout reason

Thread 1 "server" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
warning: 44	./nptl/pthread_kill.c: No such file or directory
(gdb) backtrace
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff784527e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff78288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555dd62d2 in amqp_abort ()
#6  0x0000555555ddcc28 in wait_frame_inner ()
#7  0x0000555555ddde9f in amqp_simple_wait_frame_noblock ()
#8  0x0000555555dd7cf6 in amqp_consume_message ()
#9  0x000055555595a501 in ConsumeMessage(std::function<void (char const*, int)>, char const*, char const*, int const&, int const&, bool, int) ()
#10 0x00005555558376e5 in Init() ()
#11 0x00005555557b50a9 in main ()

```

@alanxz
