### ISSUE TITLE
LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by 0x34d** [alanxz/rabbitmq-c#735]
```
Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x51e047 in malloc (/home/Ez/project/rabbitmq-c/build/fuzz/fuzz_table+0x51e047) (BuildId: b20c4a1e33b10e8d9c78e442083b933bc7f65733)
    #1 0x565a90 in record_pool_block /home/Ez/project/rabbitmq-c/librabbitmq/amqp_mem.c:64:20
    #2 0x5648c6 in amqp_pool_alloc /home/Ez/project/rabbitmq-c/librabbitmq/amqp_mem.c:115:10
    #3 0x56a8de in amqp_decode_table /home/Ez/project/rabbitmq-c/librabbitmq/amqp_table.c:154:7
    #4 0x560f07 in LLVMFuzzerTestOneInput /home/Ez/project/rabbitmq-c/fuzz/fuzz_table.c:24:12
    #5 0x44ac31 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/Ez/project/rabbitmq-c/build/fuzz/fuzz_table+0x44ac31) (BuildId: b20c4a1e33b10e8d9c78e442083b933bc7f65733)
    #6 0x42acef in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/Ez/project/rabbitmq-c/build/fuzz/fuzz_table+0x42acef) (BuildId: b20c4a1e33b10e8d9c78e442083b933bc7f65733)
    #7 0x4322f0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/Ez/project/rabbitmq-c/build/fuzz/fuzz_table+0x4322f0) (BuildId: b20c4a1e33b10e8d9c78e442083b933bc7f65733)
    #8 0x421a36 in main (/home/Ez/project/rabbitmq-c/build/fuzz/fuzz_table+0x421a36) (BuildId: b20c4a1e33b10e8d9c78e442083b933bc7f65733)
    #9 0x7f3e1d59d54f in __libc_start_call_main (/lib64/libc.so.6+0x2954f) (BuildId: 9b7d731d92528db48798ae00fd91905fc0904736)

```
```
run:
./fuzz_table bug.gz
```

[bug.gz](https://github.com/alanxz/rabbitmq-c/files/9060754/bug.gz)

**Comment by alanxz** [comment]
This is likely fixed as of: #759
